# Dockerfile para desenvolvimento do frontend com hot reload
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY babel.config.json ./
COPY webpack.config.js ./

RUN npm install

COPY src/ ./src/
COPY public/ ./public/

EXPOSE 3000

CMD ["npm", "start"]
